### ISSUE TITLE
Improve errorcode differentiation

### ISSUE THREAD

**Issue by jrfnl** [sirbrillig/phpcs-variable-analysis#175]
```php
function foo($paramUnusedBeforeUsed, $paramUsed, $paramUnused) {
    $index = 1;
    echo $paramUsed;
}
```

Both the unused `$paramUnusedBeforeUsed` and `$paramUnused` as well as the unused `$index` currently have the same error code: `UnusedVariable`.

While I realize that the `allowUnusedFunctionParameters` and `allowUnusedParametersBeforeUsed` properties exist, those can only be set for a complete code base, while differentiation via error codes gives more control, i.e. you can include/exclude select files for certain error codes.

```xml
<rule ref="VariableAnalysis"/>
<rule ref="VariableAnalysis.CodeAnalysis.VariableAnalysis.ErrorCode">
    <exclude-pattern>/src/specific-directory/*\.php$</exclude-pattern>
    <exclude-pattern>/src/specific-file\.php$</exclude-pattern>
</rule>
```

Unused parameters cannot always be "solved" as the method signature of a class method where the class extends a parent and/or implements an interface, has to be compatible with the parent class/interface.

Unused variables defined within a function is another matter.

With that in mind, I'd like to propose to split the `UnusedVariable` error code into three distinct error codes:
* `UnusedParameterBeforeUsed`
* `UnusedParameter[AfterUsed]`
* `UnusedVariable`

This would also pave the way to removing the `allowUnusedFunctionParameters` and `allowUnusedParametersBeforeUsed` properties.

As the next version is intended to be a major tag, now would probably be a good time to make such a change.

To make the BC-break smaller, I'd like to suggest for the properties to be deprecated in this major and only removed in the next major release.

For the time being, the properties could then still be checked to determine whether the `UnusedParameter...` errors should be thrown or not, giving people some time to switch over to using the error code exclusion instead of the properties.

**Comment by sirbrillig** [comment]
Sounds like a good idea. 

Relatedly, there's a [long-standing request](https://github.com/sirbrillig/phpcs-variable-analysis/issues/98#issuecomment-514084326) to split up the sniff codes for undefined variables and using an undefined variable that we've already warned you about. What do you think about that? It seems very edge-casey to me, but I'm open to ideas.

**Comment by sirbrillig** [comment]
> This would also pave the way to removing the allowUnusedFunctionParameters and allowUnusedParametersBeforeUsed properties.

I like the idea of having fewer options in general, but is there a compelling reason to remove these options rather than just leaving them and also having the different sniff codes? I'm not against the idea, but I'm just trying to understand your thoughts.

> To make the BC-break smaller, I'd like to suggest for the properties to be deprecated in this major and only removed in the next major release.

Any suggestions about how we could deprecate them? I mean, how to notify users of the deprecation?

**Comment by jrfnl** [comment]
> is there a compelling reason to remove these options rather than just leaving them and also having the different sniff codes?

Less user confusion. When both options are available and overlap, you can expect more support questions from people not understanding the difference between error codes and properties and they work ;-)

> Any suggestions about how we could deprecate them? I mean, how to notify users of the deprecation?

We've done this a few times in WPCS, I'd need to search for the commits, but what we did was basically throw a deprecation warning when the property was set to anything other than the default value. To prevent the sniff from throwing that warning on every file, we kept track of whether the deprecation warning had been thrown already and if so, skipped the check.

**Comment by jrfnl** [comment]
Here's one where we deprecated a sniff + a property in it and tracked whether the warning was thrown https://github.com/WordPress/WordPress-Coding-Standards/pull/1807/files

**Comment by sirbrillig** [comment]
Oh, it adds an actual warning during the scan. Clever! Ok, we can try that.

**Comment by sirbrillig** [comment]
The tricky thing here is that `allowUnusedParametersBeforeUsed` is turned on by default. So if we add a new sniff code for `UnusedParameterBeforeUsed`, in order to mimic the current behavior (which I think most users would still want) we'll need to somehow disable that warning by default. 

I thought perhaps we could make that warning have a `0` severity, but `0` passed to `addWarning()` causes the default severity to be used. 

We could set the severity to 0 in the `ruleset.xml` that comes with the sniff, but I'm not sure that's a good and safe solution (but maybe it is!).

Any thoughts about how to resolve this?

**Comment by jrfnl** [comment]
Let me think it over. I'll get back to you when my thoughts on it are clearer (bit late at night for me atm).

**Comment by paulschreiber** [comment]
+1 this. The "unused function parameter" warnings are irritating and not fixable. At the least, having this as their own error code would allow me to silence them.

**Comment by sirbrillig** [comment]
@paulschreiber I got this nearly complete, but ended up stalled because of a [fundamental problem](https://github.com/sirbrillig/phpcs-variable-analysis/pull/195#issuecomment-671639246) that I don't know how to solve. If you have any ideas, I'd love to get it in as part of 3.0.

**Comment by paulschreiber** [comment]
I'm okay with showing more warnings by default and letting users ignore them in `phpcs.xml`.

**Comment by sirbrillig** [comment]
That's definitely an option, but here's my train of thought; let me know what you think.

If we do nothing, then folks who don't like that unused function parameters after used ones are warnings need to turn on the existing `allowUnusedFunctionParameters` option. My (admittedly unscientific) guess is that this is a smaller number of people than those who just want to ignore unused parameters before used ones. I totally understand that if you're overriding an existing method then changing the signature is not a simple thing, but I think that as far as the community of PHP developers go, there are fewer methods being overridden than new functions being made.

In addition, even if we do replace it with a new sniff code, that means that people who want to ignore these warnings _still have to change something_. They just have to disable the sniff code rather than set the `allowUnusedFunctionParameters` option. It doesn't reduce the amount of work for those people but _does increase_ the amount of work for people who don't want to see warnings for unused variables before used ones, since they now have to ignore that error code explicitly when previously it was the default.

**Comment by paulschreiber** [comment]
My main use case is implementing WordPress filters and action. It is very common to only use a subset of the passed-in parameters in such a function, and I don't want to see warnings in this case.

**Comment by sirbrillig** [comment]
Yes, and I totally get that, but my point is that you can just turn on `allowUnusedFunctionParameters` and you won't see them. What is the advantage of making a separate sniff code?

**Comment by paulschreiber** [comment]
Having different classes of problems reported differently seems correct and useful.

**Comment by sirbrillig** [comment]
I very much agree, but it doesn't seem worth making life harder for developers to do so. I'd like to find a way to have more specific sniff codes while still ignoring the warnings about unused before used parameters by default. That's what I'm trying to come with a solution for.

**Comment by paulschreiber** [comment]
I've enabled `allowUnusedFunctionParameters` in my project, which solves the problem for now.

**Comment by sirbrillig** [comment]
Actually, I did have one idea. We could add the different sniff codes, but not deprecate or remove `allowUnusedFunctionParameters` or `allowUnusedParametersBeforeUsed`. Since the latter could remain true by default, the effect would be that folks would get the same behavior they get now, but there would also be new error codes (one of which would never be seen unless you turned off `allowUnusedParametersBeforeUsed`).
