### ISSUE TITLE
Support of array desctructing

### ISSUE THREAD

**Issue by shvlv** [sirbrillig/phpcs-variable-analysis#271]
For the following snippet:
```php
<?php

$post = $data['post'];
```
I got the internal error: `An error occurred during processing; checking has been aborted. The error message was: Could not find start of statement on line 3 (Internal.Exception)`

It is apparently caused by https://github.com/sirbrillig/phpcs-variable-analysis/blob/2.x/VariableAnalysis/Sniffs/CodeAnalysis/VariableAnalysisSniff.php#L1320. 

Does sniff support array destructing?

**Comment by sirbrillig** [comment]
Thank you! This was a regression added by the recent changes to scanning for static variables (https://github.com/sirbrillig/phpcs-variable-analysis/pull/267). I didn't have a test for variable access at the top of a file. This will be fixed by https://github.com/sirbrillig/phpcs-variable-analysis/pull/274

> Does sniff support array destructing?

Yes, it does.

**Comment by shvlv** [comment]
Oh, I've just realized I put wrong spinnet initially (should be `['post' => $post] = $data;`). But your PR fixes both cases, true. Thank you!
