### ISSUE TITLE
Automate tests

### ISSUE THREAD

**Issue by sirbrillig** [sirbrillig/phpcs-variable-analysis#8]
The tests should be able to run with a simple call to `composer test`.

**Comment by GaryJones** [comment]
It would be good to get some instructions written up as well, even if the tests are ultimately then available via `composer test`.

I started to put together something to run the tests, but seemed to be going down a rabbit hole that may not have been necessary. I guess you'd been running tests already, but I hadn't figured out how you were doing that.

Do be aware though, that it should cater for PHPUnit and PHPCS NOT being available globally - i.e. they should be `require-dev` dependencies, and any paths to them reference `vendor/bin/php*` instead of global installs.

Tieing this all into a Travis CI webhook would be the obvious next step afterwards.

**Comment by sirbrillig** [comment]
Now the tests can be run with `composer test`. I made #15 to cover adding CI.
